### ISSUE TITLE
Suggestion: Register to OpenUPM with the upm branch

### ISSUE THREAD

**Issue by De-Panther** [colyseus/colyseus-unity-sdk#162]
The https://openupm.com/ site has a list of lots of Unity packages, and runs its own scoped registry.
It makes the use of external UPMs easier than Git UPMs.

**Comment by endel** [comment]
Thanks for the suggestion! This has been done in a while and forgot to update here 🙏  https://openupm.com/packages/io.colyseus.sdk/
