### ISSUE TITLE
about 0.15 state.player.listen("field", (value))

### ISSUE THREAD

**Issue by yty** [colyseus/colyseus-unity-sdk#219]
[Schema's onChange behaviour change](https://docs.colyseus.io/migrating/0.15/?h=onadd#schema-callbacks-api-slightly-changed)](https://docs.colyseus.io/migrating/0.15/?h=onadd#schema-callbacks-api-slightly-changed)

```
// 0.15 (new)
state.player.onChange(() =>{
    console.log("player changed!");
});
state.player.listen("field", (value) => {
    console.log(value);
})
```

I can't find the listen method in c#. How can I use it?

![image](https://github.com/colyseus/colyseus-unity-sdk/assets/841770/3ce9b9b7-199a-4831-bf15-e7528ace7aa8)

**Comment by yty** [comment]
using Colyseus.Schema;

public partial class Player : Schema
{
	[Type(0, "number")]
	public float x = default(float);

	[Type(1, "number")]
	public float y = default(float);
}

**Comment by endel** [comment]
Hi @yty, the `schema-codegen` tool is responsible for generating the listeners per property on C#

**Comment by yty** [comment]
@endel 

thank you, I understand.
Suggest adding it to Example by default.

0.15.5 \ Example \ Scripts \ Scheme \ MyRoomState.cs
0.15.5 \ Example \ Scripts \ Scheme \ Player.cs
