### ISSUE TITLE
State with nested collection schema data broken after patch

### ISSUE THREAD

**Issue by gregharding** [colyseus/colyseus-unity-sdk#230]
Our room state contains nested collection schema data and is breaking after initial connection and state synchronisation when the gateway sends the first state patch down. We're seeing this issue intermittently, only happening directly after every 3 or 4 connections, but this is probably unrelated to the core issue when the state is patched.

We traced the issue to the room state patching `MapSchema` and `ArraySchema` objects. After state patching, `MapSchema`s and `ArraySchema`s are being corrupted, losing their internal indexing. The cause is that during a `MapSchema.Clone()` or `ArraySchema.Clone()` the main data and callbacks are copied or assigned but the internal indexes are not.

The fix is to ensure that the internal indexes are also assigned or copied in `Clone()` methods.

Adding this issue so pull request with fix can reference it.

**Comment by endel** [comment]
Thank you so much for the fix @gregharding 🙌  Just released [0.15.12](https://github.com/colyseus/colyseus-unity-sdk/releases/tag/0.15.12) with your fix.
